/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import datapackage.SaveData;
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import pojopackage.PojoRGPV;

public class StorRecord extends javax.swing.JFrame {

    public StorRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        age_T = new javax.swing.JTextField();
        math_T = new javax.swing.JTextField();
        chemistry_T = new javax.swing.JTextField();
        year_T = new javax.swing.JTextField();
        english_T = new javax.swing.JTextField();
        hindi_T = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        physics_T = new javax.swing.JTextField();
        branch_T = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();
        sem_T = new javax.swing.JComboBox<>();
        course_T = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        rgNo_T = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 210, 249));

        jPanel2.setBackground(new java.awt.Color(182, 185, 168));

        jLabel1.setBackground(new java.awt.Color(204, 140, 140));
        jLabel1.setFont(new java.awt.Font("HP Simplified Jpan", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STORE STUDENT DATA");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("COURSE                              :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("YEAR                                      :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("SEMESTER                             :");

        Submit.setBackground(new java.awt.Color(36, 139, 150));
        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.setFocusPainted(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("PHYSICS                             :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("CHEMISTRY                        :");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("AGE                                :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("ENGLISH                                :");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("HINDI                                     :");

        age_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_TActionPerformed(evt);
            }
        });
        age_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                age_TKeyReleased(evt);
            }
        });

        math_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                math_TActionPerformed(evt);
            }
        });
        math_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                math_TKeyReleased(evt);
            }
        });

        chemistry_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistry_TActionPerformed(evt);
            }
        });
        chemistry_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chemistry_TKeyReleased(evt);
            }
        });

        year_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_TActionPerformed(evt);
            }
        });
        year_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                year_TKeyReleased(evt);
            }
        });

        english_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                english_TActionPerformed(evt);
            }
        });
        english_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                english_TKeyReleased(evt);
            }
        });

        hindi_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hindi_TActionPerformed(evt);
            }
        });
        hindi_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hindi_TKeyReleased(evt);
            }
        });

        back1.setBackground(new java.awt.Color(36, 139, 150));
        back1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("Back");
        back1.setFocusPainted(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("MATH                                 : ");

        physics_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physics_TActionPerformed(evt);
            }
        });
        physics_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                physics_TKeyReleased(evt);
            }
        });

        branch_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branch_TActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("BRANCH                                 :");

        message.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(51, 204, 0));

        warning.setBackground(new java.awt.Color(255, 0, 0));
        warning.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        sem_T.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sem_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th", "6th" }));

        course_T.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        course_T.setForeground(new java.awt.Color(255, 255, 255));
        course_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSC", "B.COM", "BCA", "BTECH", "BBA" }));
        course_T.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Registration no        :");
        jLabel10.setOpaque(true);

        rgNo_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgNo_TActionPerformed(evt);
            }
        });
        rgNo_T.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rgNo_TKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chemistry_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(math_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(physics_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(age_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(course_T, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sem_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(english_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hindi_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branch_T, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(688, 688, 688)
                            .addComponent(rgNo_T, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(468, 468, 468)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(96, 96, 96)
                                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sem_T, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branch_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(english_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hindi_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(course_T, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(age_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(chemistry_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(math_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(physics_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rgNo_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        PojoRGPV pjt[] = new PojoRGPV[100];
        int rgNo = Integer.parseInt(rgNo_T.getText());//

        if (branch_T.getText().isEmpty()
                || year_T.getText().isEmpty()
                || chemistry_T.getText().isEmpty()
                || physics_T.getText().isEmpty()
                || math_T.getText().isEmpty()
                || age_T.getText().isEmpty()
                || hindi_T.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fil all the details");
        } else try {
            if (new SaveData().checkRegistration(rgNo)) {
                JOptionPane.showMessageDialog(null, "Registration number invalid ");
            } else if (new SaveData().rollCheck(rgNo)) {

                JOptionPane.showMessageDialog(null, "allready have details");

            } else {
                try {

                    String branch = branch_T.getText();

                    String course = course_T.getSelectedItem().toString();

                    String sem = sem_T.getSelectedItem().toString();
                    int year = Integer.parseInt(year_T.getText());
                    int chemistry = Integer.parseInt(chemistry_T.getText());
                    int physics = Integer.parseInt(physics_T.getText());
                    int math = Integer.parseInt(math_T.getText());
                    int english = Integer.parseInt(english_T.getText());
                    int age = Integer.parseInt(age_T.getText());
                    int hindi = Integer.parseInt(hindi_T.getText());
                    //int roll = Integer.parseInt(roll_T.getText());
                    if (physics < 0 || chemistry < 0 || math < 0 || hindi < 0 || english < 0 || physics > 100 || chemistry > 100 || math > 100 || hindi > 100 || english > 100) {
                        JOptionPane.showMessageDialog(null, "invalid mark");
                        message.setText("invalid mark");
                    } else if (year < 0 || year > 2025) {
                        JOptionPane.showMessageDialog(null, "invalid year");
                    } else if (age < 0) {
                        JOptionPane.showMessageDialog(null, "invalid age");
                    } else {
                        int total = chemistry + physics + math + hindi + english;
                        double per = total / 5;

                        int n = 1;      //firstname, lastname, fname, mname,
                        pjt[1] = new PojoRGPV(course, branch, sem, age, year, physics, chemistry, math, hindi, english, total, per,rgNo);
                        try {
                            SaveData.saveData(pjt, n);

                            message.setForeground(Color.green);
                            message.setText("Submit success");
                        } catch (ClassNotFoundException | SQLException e) {
                            message.setForeground(Color.red);
                            message.setText("submit Faild");

                            System.out.println(e);
                        }
                    }

                } catch (NumberFormatException e) {

                    JOptionPane.showMessageDialog(null, "invalid Details");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(StorRecord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StorRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void age_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_TActionPerformed

    private void math_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_math_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_math_TActionPerformed

    private void chemistry_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistry_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemistry_TActionPerformed

    private void english_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_english_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_english_TActionPerformed

    private void hindi_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hindi_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hindi_TActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed

        new AdminOp().setVisible(true);
        dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void physics_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physics_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physics_TActionPerformed

    private void branch_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branch_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branch_TActionPerformed

    private void chemistry_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemistry_TKeyReleased

        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid mark !!");
            chemistry_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            chemistry_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }
    }//GEN-LAST:event_chemistry_TKeyReleased

    private void math_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_math_TKeyReleased

        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid mark !!");
            math_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            math_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }
    }//GEN-LAST:event_math_TKeyReleased

    private void physics_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_physics_TKeyReleased

        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid mark !!");
            physics_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            physics_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }
    }//GEN-LAST:event_physics_TKeyReleased

    private void english_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_english_TKeyReleased

        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid mark !!");
            english_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            english_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_english_TKeyReleased

    private void hindi_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hindi_TKeyReleased
        // TODO add your handling code here:

        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid mark !!");
            hindi_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            hindi_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }
    }//GEN-LAST:event_hindi_TKeyReleased

    private void age_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_TKeyReleased
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid age !!");
            age_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            age_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }

    }//GEN-LAST:event_age_TKeyReleased

    private void year_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_year_TKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() < 48 || evt.getKeyChar() > 57) {
            warning.setText("invalid year !!");
            year_T.setBorder(javax.swing.BorderFactory.createLineBorder(red));
        } else {
            warning.setText(" ");
            year_T.setBorder(javax.swing.BorderFactory.createLineBorder(black));
        }
    }//GEN-LAST:event_year_TKeyReleased

    private void year_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_TActionPerformed

    private void rgNo_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgNo_TActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgNo_TActionPerformed

    private void rgNo_TKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rgNo_TKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rgNo_TKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorRecord.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorRecord.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorRecord.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorRecord.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField age_T;
    private javax.swing.JButton back1;
    private javax.swing.JTextField branch_T;
    private javax.swing.JTextField chemistry_T;
    private javax.swing.JComboBox<String> course_T;
    private javax.swing.JTextField english_T;
    private javax.swing.JTextField hindi_T;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField math_T;
    private javax.swing.JLabel message;
    private javax.swing.JTextField physics_T;
    private javax.swing.JTextField rgNo_T;
    private javax.swing.JComboBox<String> sem_T;
    private javax.swing.JLabel warning;
    private javax.swing.JTextField year_T;
    // End of variables declaration//GEN-END:variables
}
